name: 'Kingly'
type: 'Site'
description: Installs other recipes to kickstart a site.
recipes:
  - velir_base
  - ddr_security_seckit
  - drupal_cms_image
  - drupal_cms_search

config:
  strict: false
  actions:
    gin.settings:
      simple_config_update:
        classic_toolbar: new
        enable_darkmode: auto
