name: 'Kingly'
type: 'Site'
description: Installs other recipes to kickstart a site.
recipes:
  # Core recipes
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/basic_html_format_editor
  # External recipes
  - ddr_security_seckit
  - gin-admin-experience
  # Drupal CMS recipes
  - drupal_cms_image
  - drupal_cms_search
  # Kingly recipes
  - kingly_frontend
  - kingly_page
  - kingly_paragraph_text
  - kingly_paragraph_media
  - kingly_paragraph_card
  - kingly_paragraph_accordion

install:
  - config
  - node
  - user
  - text
  - link
  - filter
  - block
  - block_content
  - ckeditor5
  - contextual
  - menu_link_content
  - datetime
  - block_content
  - editor
  - image
  - menu_ui
  - options
  - path
  - dynamic_page_cache
  - big_pipe
  - taxonomy
  - dblog
  - toolbar
  - field_ui
  - media
  - media_library
  - views
  - views_ui
  - automated_cron
  - pathauto
  - redirect
  - metatag
  - metatag_open_graph
  - metatag_verification
  - field_group
  - coffee
  - kingly_sdc
  - admin_toolbar
  - admin_toolbar_tools

config:
  strict: false
  import:
    dblog: '*'
    image: '*'
    media: '*'
    media_library: '*'
    pathauto: '*'
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    node:
      - views.view.content
    user:
      - views.view.user_admin_people
  actions:
    gin.settings:
      simple_config_update:
        classic_toolbar: horizontal
        show_user_theme_settings: true
        enable_darkmode: auto
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    node.settings:
      simple_config_update:
        use_admin_theme: true
