name: 'Kingly'
type: 'Site'
description: Installs other recipes to kickstart a site.
recipes:
  - drupal_cms_admin_ui
  - ddr_security_seckit
  - drupal_cms_image
  - drupal_cms_search

install:
  - field_group
  - coffee
  - kingly_sdc
  - menu_ui
  - menu_link_content

config:
  strict: false
  actions:
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
    block.block.gin_tools:
      simple_config_update:
        status: false
    gin.settings:
      simple_config_update:
        classic_toolbar: new
        enable_darkmode: auto
